<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ProjectManagementXarelto.Core\ProjectManagementXarelto.Core.csproj" />
    <ProjectReference Include="..\ProjectManagementXarelto.Data\ProjectManagementXarelto.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
